#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_SIEU_THI_LTCSDL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSieuThiMini")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Admin(tbl_Admin instance);
    partial void Updatetbl_Admin(tbl_Admin instance);
    partial void Deletetbl_Admin(tbl_Admin instance);
    partial void Inserttbl_Product(tbl_Product instance);
    partial void Updatetbl_Product(tbl_Product instance);
    partial void Deletetbl_Product(tbl_Product instance);
    partial void Inserttbl_ProductCategory(tbl_ProductCategory instance);
    partial void Updatetbl_ProductCategory(tbl_ProductCategory instance);
    partial void Deletetbl_ProductCategory(tbl_ProductCategory instance);
    partial void Inserttbl_DetailedBill(tbl_DetailedBill instance);
    partial void Updatetbl_DetailedBill(tbl_DetailedBill instance);
    partial void Deletetbl_DetailedBill(tbl_DetailedBill instance);
    partial void Inserttbl_Customer(tbl_Customer instance);
    partial void Updatetbl_Customer(tbl_Customer instance);
    partial void Deletetbl_Customer(tbl_Customer instance);
    partial void Inserttbl_Bill(tbl_Bill instance);
    partial void Updatetbl_Bill(tbl_Bill instance);
    partial void Deletetbl_Bill(tbl_Bill instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::QL_SIEU_THI_LTCSDL.Properties.Settings.Default.QLSieuThiMiniConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Admin> tbl_Admins
		{
			get
			{
				return this.GetTable<tbl_Admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Product> tbl_Products
		{
			get
			{
				return this.GetTable<tbl_Product>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ProductCategory> tbl_ProductCategories
		{
			get
			{
				return this.GetTable<tbl_ProductCategory>();
			}
		}
		
		public System.Data.Linq.Table<tbl_DetailedBill> tbl_DetailedBills
		{
			get
			{
				return this.GetTable<tbl_DetailedBill>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Customer> tbl_Customers
		{
			get
			{
				return this.GetTable<tbl_Customer>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Bill> tbl_Bills
		{
			get
			{
				return this.GetTable<tbl_Bill>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Admin")]
	public partial class tbl_Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AdminID;
		
		private string _NameOfAdmin;
		
		private string _TelOfAdmin;
		
		private string _UsernameOfAdmin;
		
		private string _PasswordOfAdmin;
		
		private string _AuthorizationOfAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnNameOfAdminChanging(string value);
    partial void OnNameOfAdminChanged();
    partial void OnTelOfAdminChanging(string value);
    partial void OnTelOfAdminChanged();
    partial void OnUsernameOfAdminChanging(string value);
    partial void OnUsernameOfAdminChanged();
    partial void OnPasswordOfAdminChanging(string value);
    partial void OnPasswordOfAdminChanged();
    partial void OnAuthorizationOfAdminChanging(string value);
    partial void OnAuthorizationOfAdminChanged();
    #endregion
		
		public tbl_Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfAdmin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NameOfAdmin
		{
			get
			{
				return this._NameOfAdmin;
			}
			set
			{
				if ((this._NameOfAdmin != value))
				{
					this.OnNameOfAdminChanging(value);
					this.SendPropertyChanging();
					this._NameOfAdmin = value;
					this.SendPropertyChanged("NameOfAdmin");
					this.OnNameOfAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelOfAdmin", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TelOfAdmin
		{
			get
			{
				return this._TelOfAdmin;
			}
			set
			{
				if ((this._TelOfAdmin != value))
				{
					this.OnTelOfAdminChanging(value);
					this.SendPropertyChanging();
					this._TelOfAdmin = value;
					this.SendPropertyChanged("TelOfAdmin");
					this.OnTelOfAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsernameOfAdmin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string UsernameOfAdmin
		{
			get
			{
				return this._UsernameOfAdmin;
			}
			set
			{
				if ((this._UsernameOfAdmin != value))
				{
					this.OnUsernameOfAdminChanging(value);
					this.SendPropertyChanging();
					this._UsernameOfAdmin = value;
					this.SendPropertyChanged("UsernameOfAdmin");
					this.OnUsernameOfAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordOfAdmin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PasswordOfAdmin
		{
			get
			{
				return this._PasswordOfAdmin;
			}
			set
			{
				if ((this._PasswordOfAdmin != value))
				{
					this.OnPasswordOfAdminChanging(value);
					this.SendPropertyChanging();
					this._PasswordOfAdmin = value;
					this.SendPropertyChanged("PasswordOfAdmin");
					this.OnPasswordOfAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorizationOfAdmin", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AuthorizationOfAdmin
		{
			get
			{
				return this._AuthorizationOfAdmin;
			}
			set
			{
				if ((this._AuthorizationOfAdmin != value))
				{
					this.OnAuthorizationOfAdminChanging(value);
					this.SendPropertyChanging();
					this._AuthorizationOfAdmin = value;
					this.SendPropertyChanged("AuthorizationOfAdmin");
					this.OnAuthorizationOfAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Product")]
	public partial class tbl_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductID;
		
		private string _NameOfProduct;
		
		private int _NumberOfProduct;
		
		private int _ProductCategoryID;
		
		private int _PriceOfProduct;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductIDChanging(int value);
    partial void OnProductIDChanged();
    partial void OnNameOfProductChanging(string value);
    partial void OnNameOfProductChanged();
    partial void OnNumberOfProductChanging(int value);
    partial void OnNumberOfProductChanged();
    partial void OnProductCategoryIDChanging(int value);
    partial void OnProductCategoryIDChanged();
    partial void OnPriceOfProductChanging(int value);
    partial void OnPriceOfProductChanged();
    #endregion
		
		public tbl_Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this.OnProductIDChanging(value);
					this.SendPropertyChanging();
					this._ProductID = value;
					this.SendPropertyChanged("ProductID");
					this.OnProductIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfProduct", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NameOfProduct
		{
			get
			{
				return this._NameOfProduct;
			}
			set
			{
				if ((this._NameOfProduct != value))
				{
					this.OnNameOfProductChanging(value);
					this.SendPropertyChanging();
					this._NameOfProduct = value;
					this.SendPropertyChanged("NameOfProduct");
					this.OnNameOfProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfProduct", DbType="Int NOT NULL")]
		public int NumberOfProduct
		{
			get
			{
				return this._NumberOfProduct;
			}
			set
			{
				if ((this._NumberOfProduct != value))
				{
					this.OnNumberOfProductChanging(value);
					this.SendPropertyChanging();
					this._NumberOfProduct = value;
					this.SendPropertyChanged("NumberOfProduct");
					this.OnNumberOfProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategoryID", DbType="Int NOT NULL")]
		public int ProductCategoryID
		{
			get
			{
				return this._ProductCategoryID;
			}
			set
			{
				if ((this._ProductCategoryID != value))
				{
					this.OnProductCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._ProductCategoryID = value;
					this.SendPropertyChanged("ProductCategoryID");
					this.OnProductCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceOfProduct", DbType="Int NOT NULL")]
		public int PriceOfProduct
		{
			get
			{
				return this._PriceOfProduct;
			}
			set
			{
				if ((this._PriceOfProduct != value))
				{
					this.OnPriceOfProductChanging(value);
					this.SendPropertyChanging();
					this._PriceOfProduct = value;
					this.SendPropertyChanged("PriceOfProduct");
					this.OnPriceOfProductChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ProductCategory")]
	public partial class tbl_ProductCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductCategoryID;
		
		private string _NameOfProductCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductCategoryIDChanging(int value);
    partial void OnProductCategoryIDChanged();
    partial void OnNameOfProductCategoryChanging(string value);
    partial void OnNameOfProductCategoryChanged();
    #endregion
		
		public tbl_ProductCategory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCategoryID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductCategoryID
		{
			get
			{
				return this._ProductCategoryID;
			}
			set
			{
				if ((this._ProductCategoryID != value))
				{
					this.OnProductCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._ProductCategoryID = value;
					this.SendPropertyChanged("ProductCategoryID");
					this.OnProductCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfProductCategory", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NameOfProductCategory
		{
			get
			{
				return this._NameOfProductCategory;
			}
			set
			{
				if ((this._NameOfProductCategory != value))
				{
					this.OnNameOfProductCategoryChanging(value);
					this.SendPropertyChanging();
					this._NameOfProductCategory = value;
					this.SendPropertyChanged("NameOfProductCategory");
					this.OnNameOfProductCategoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_DetailedBill")]
	public partial class tbl_DetailedBill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBill;
		
		private int _IDProduct;
		
		private int _Amount;
		
		private int _UnitPrice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBillChanging(int value);
    partial void OnIDBillChanged();
    partial void OnIDProductChanging(int value);
    partial void OnIDProductChanged();
    partial void OnAmountChanging(int value);
    partial void OnAmountChanged();
    partial void OnUnitPriceChanging(int value);
    partial void OnUnitPriceChanged();
    #endregion
		
		public tbl_DetailedBill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBill", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBill
		{
			get
			{
				return this._IDBill;
			}
			set
			{
				if ((this._IDBill != value))
				{
					this.OnIDBillChanging(value);
					this.SendPropertyChanging();
					this._IDBill = value;
					this.SendPropertyChanged("IDBill");
					this.OnIDBillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDProduct", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDProduct
		{
			get
			{
				return this._IDProduct;
			}
			set
			{
				if ((this._IDProduct != value))
				{
					this.OnIDProductChanging(value);
					this.SendPropertyChanging();
					this._IDProduct = value;
					this.SendPropertyChanged("IDProduct");
					this.OnIDProductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int NOT NULL")]
		public int Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Int NOT NULL")]
		public int UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this.OnUnitPriceChanging(value);
					this.SendPropertyChanging();
					this._UnitPrice = value;
					this.SendPropertyChanged("UnitPrice");
					this.OnUnitPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Customer")]
	public partial class tbl_Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomerID;
		
		private string _NameOfCustomer;
		
		private string _TelOfCustomer;
		
		private string _EmailOfCustomer;
		
		private string _AddressOfCustomer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIDChanging(int value);
    partial void OnCustomerIDChanged();
    partial void OnNameOfCustomerChanging(string value);
    partial void OnNameOfCustomerChanged();
    partial void OnTelOfCustomerChanging(string value);
    partial void OnTelOfCustomerChanged();
    partial void OnEmailOfCustomerChanging(string value);
    partial void OnEmailOfCustomerChanged();
    partial void OnAddressOfCustomerChanging(string value);
    partial void OnAddressOfCustomerChanged();
    #endregion
		
		public tbl_Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOfCustomer", DbType="NVarChar(100)")]
		public string NameOfCustomer
		{
			get
			{
				return this._NameOfCustomer;
			}
			set
			{
				if ((this._NameOfCustomer != value))
				{
					this.OnNameOfCustomerChanging(value);
					this.SendPropertyChanging();
					this._NameOfCustomer = value;
					this.SendPropertyChanged("NameOfCustomer");
					this.OnNameOfCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelOfCustomer", DbType="NVarChar(10)")]
		public string TelOfCustomer
		{
			get
			{
				return this._TelOfCustomer;
			}
			set
			{
				if ((this._TelOfCustomer != value))
				{
					this.OnTelOfCustomerChanging(value);
					this.SendPropertyChanging();
					this._TelOfCustomer = value;
					this.SendPropertyChanged("TelOfCustomer");
					this.OnTelOfCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailOfCustomer", DbType="NVarChar(100)")]
		public string EmailOfCustomer
		{
			get
			{
				return this._EmailOfCustomer;
			}
			set
			{
				if ((this._EmailOfCustomer != value))
				{
					this.OnEmailOfCustomerChanging(value);
					this.SendPropertyChanging();
					this._EmailOfCustomer = value;
					this.SendPropertyChanged("EmailOfCustomer");
					this.OnEmailOfCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressOfCustomer", DbType="NVarChar(100)")]
		public string AddressOfCustomer
		{
			get
			{
				return this._AddressOfCustomer;
			}
			set
			{
				if ((this._AddressOfCustomer != value))
				{
					this.OnAddressOfCustomerChanging(value);
					this.SendPropertyChanging();
					this._AddressOfCustomer = value;
					this.SendPropertyChanged("AddressOfCustomer");
					this.OnAddressOfCustomerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Bill")]
	public partial class tbl_Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BillID;
		
		private int _BilledDate;
		
		private int _AdminID;
		
		private System.Nullable<int> _CustomerID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBillIDChanging(int value);
    partial void OnBillIDChanged();
    partial void OnBilledDateChanging(int value);
    partial void OnBilledDateChanged();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnCustomerIDChanging(System.Nullable<int> value);
    partial void OnCustomerIDChanged();
    #endregion
		
		public tbl_Bill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BillID
		{
			get
			{
				return this._BillID;
			}
			set
			{
				if ((this._BillID != value))
				{
					this.OnBillIDChanging(value);
					this.SendPropertyChanging();
					this._BillID = value;
					this.SendPropertyChanged("BillID");
					this.OnBillIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BilledDate", DbType="Int NOT NULL")]
		public int BilledDate
		{
			get
			{
				return this._BilledDate;
			}
			set
			{
				if ((this._BilledDate != value))
				{
					this.OnBilledDateChanging(value);
					this.SendPropertyChanging();
					this._BilledDate = value;
					this.SendPropertyChanged("BilledDate");
					this.OnBilledDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", DbType="Int NOT NULL")]
		public int AdminID
		{
			get
			{
				return this._AdminID;
			}
			set
			{
				if ((this._AdminID != value))
				{
					this.OnAdminIDChanging(value);
					this.SendPropertyChanging();
					this._AdminID = value;
					this.SendPropertyChanged("AdminID");
					this.OnAdminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int")]
		public System.Nullable<int> CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
