<?xml version="1.0" encoding="utf-8"?><Database Name="QLSieuThiMini" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLSieuThiMini;Integrated Security=True" SettingsObjectName="QL_SIEU_THI_LTCSDL.Properties.Settings" SettingsPropertyName="QLSieuThiMiniConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Admin" Member="tbl_Admins">
    <Type Name="tbl_Admin">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameOfAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TelOfAdmin" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UsernameOfAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordOfAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorizationOfAdmin" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Product" Member="tbl_Products">
    <Type Name="tbl_Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameOfProduct" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfProduct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceOfProduct" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_ProductCategory" Member="tbl_ProductCategories">
    <Type Name="tbl_ProductCategory">
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameOfProductCategory" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DetailedBill" Member="tbl_DetailedBills">
    <Type Name="tbl_DetailedBill">
      <Column Name="IDBill" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDProduct" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Amount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Customer" Member="tbl_Customers">
    <Type Name="tbl_Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameOfCustomer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TelOfCustomer" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EmailOfCustomer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressOfCustomer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Bill" Member="tbl_Bills">
    <Type Name="tbl_Bill">
      <Column Name="BillID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BilledDate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>