<?xml version="1.0" encoding="utf-8"?><Database Name="QLSieuThiMini" Class="DataAdminAccountDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLSieuThiMini;Integrated Security=True" SettingsObjectName="QL_SIEU_THI_LTCSDL.Properties.Settings" SettingsPropertyName="QLSieuThiMiniConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_TaiKhoan" Member="tbl_TaiKhoans">
    <Type Name="tbl_TaiKhoan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Sdt" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Quyen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_KhachHang" Member="tbl_KhachHangs">
    <Type Name="tbl_KhachHang">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Sdt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_LoaiHangHoa" Member="tbl_LoaiHangHoas">
    <Type Name="tbl_LoaiHangHoa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="tbl_LoaiHangHoa_tbl_HangHoa" Member="tbl_HangHoas" ThisKey="Id" OtherKey="IdLoaiHang" Type="tbl_HangHoa" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_HangHoa" Member="tbl_HangHoas">
    <Type Name="tbl_HangHoa">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdLoaiHang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tbl_LoaiHangHoa_tbl_HangHoa" Member="tbl_LoaiHangHoa" ThisKey="IdLoaiHang" OtherKey="Id" Type="tbl_LoaiHangHoa" IsForeignKey="true" />
    </Type>
  </Table>
</Database>